server:
  port: 8082 # Activity 서비스(8081)와 겹치지 않게 설정

spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_db # 같은 DB를 쓰거나 새로 만드세요
    username: user
    password: password # 본인의 DB 비번
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 발급받은 Gemini API 키를 여기에 넣습니다.
google:
  ai:
    api-key: AIzaSyDaqAvlYnjfXxDXTjqGWAaS5w76bK7m8bo