server:
  port: 8082 

spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_db 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

google:
  ai:
    api-key: ${GEMINI_API_KEY}