server:
  port: 8081  

spring:
  application:
    name: activity-service  

  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 앱이 실행될 때 테이블을 자동으로 생성해주는 옵션입니다.
      ddl-auto: update
    show-sql: true        # 실행되는 SQL문을 로그로 보여줍니다.
    properties:
      hibernate:
        format_sql: true  # SQL을 예쁘게 출력합니다.
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
