server:
<<<<<<< HEAD
  port: 8081  # 이 서비스는 8081 포트에서 실행됩니다.

spring:
  application:
    name: activity-service  # 서비스의 이름입니다.

  datasource:
    # 도커로 띄운 PostgreSQL 주소입니다.
    url: jdbc:postgresql://localhost:5432/fitness_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 앱이 실행될 때 테이블을 자동으로 생성해주는 옵션입니다.
      ddl-auto: update
    show-sql: true        # 실행되는 SQL문을 로그로 보여줍니다.
    properties:
      hibernate:
        format_sql: true  # SQL을 예쁘게 출력합니다.
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
=======
  port: 8082 # Activity 서비스(8081)와 겹치지 않게 설정

spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_db # 같은 DB를 쓰거나 새로 만드세요
    username: user
    password: password # 본인의 DB 비번
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 발급받은 Gemini API 키를 여기에 넣습니다.
google:
  ai:
    api-key: AIzaSyDaqAvlYnjfXxDXTjqGWAaS5w76bK7m8bo
>>>>>>> 361dc578965619684e17d0c2879a0210b8a306ef
